### ISSUE TITLE
Sanitize

### ISSUE THREAD

**Issue by johntom** [ivanph/react-native-webintent#6]
Hi,
Thanks for the repo as it's the only one I got to work with android.Would love to see 2 additional features (see react-native-htmlview but not working on android 0.19)  
1) display html
2) sanitize-html option (specifically for css and links)
TIA
John

**Comment by ivanph** [comment]
Hi John,

The purpose of this module was to be a simple stand in for the lack of a native Intent module in the first releases of RN for Android. I don't think this features should be part of this project. Now RN for Android has a native Intent module so this project is pretty much obsolete.

Cheers

**Comment by johntom** [comment]
Thanks
